name: flutter_openai_stream
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0-170.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.7
  http: ^1.2.2
  http_parser: ^4.0.2
  dio: ^5.2.1
  file_picker: ^5.2.5
  mime: ^1.0.2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  provider: ^6.1.1
  web: ^1.1.1
  uuid: ^4.4.0
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/images/icon-chatbot.png